### ISSUE TITLE
Parsed and unparsed uri is not a same

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-uri#6]
Example:
$source_uri = '/?#';
$parsed_uri = Zend\Uri\UriFactory::factory($source_uri, 'http');
$unparsed_uri = $parsed_uri->toString();
echo $unparsed_uri; // we see '/', but must be same as source uri 

It's because in Zend\Uri::toString() only host check on null. Can you fix it, please, and add check on null with other uri components? It will be more right behavior of this method.

---

Originally posted by @RubtsovAV at https://github.com/zendframework/zend-uri/issues/5

**Comment by weierophinney** [comment]
The query string and anchor are empty so there is no reason to put the '?' and '#' characters in the $unparsed_uri


---

Originally posted by @brian978 at https://github.com/zendframework/zend-uri/issues/5#issuecomment-227018068

**Comment by samsonasik** [comment]
I agree with @brian978 , it doesn't make sense to parse empty query and fragment. Handle that will make a lot of edge case bug.
