### ISSUE TITLE
PHP Fatal error:  Uncaught Laminas\Uri\Exception\InvalidUriException: URI is not valid and cannot be converted into a string

### ISSUE THREAD

**Issue by matbech** [laminas/laminas-uri#9]
The following exception is thrown under some circumstances (still debugging why):
PHP Fatal error:  Uncaught Laminas\Uri\Exception\InvalidUriException: URI is not valid and cannot be converted into a string
This exception is thrown quite a lot on a production system because of penetration testing from uninvited 3rd parties.

From the message alone it is impossible to figure out what went wrong. So it would be helpful if the URI components like scheme, host, path, query, fragment would be part of the exception message.

Something like:
throw new Exception\InvalidUriException(
                    'URI is not valid and cannot be converted into a string scheme="' . $this->scheme .'" host="' . $this->host . '", path="' . $this->path . '", query="' . $this->query .'", fragment="' . $this->fragment .'"'
                );

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [league/uri](http://uri.thephpleague.com/)

**Comment by gvasilakiss** [comment]
Getting the same error while trying to access the homepage of the website: 

`Laminas\Uri\Exception\InvalidUriException: URI is not valid and cannot be converted into a string in /var/www/html/vendor/laminas/laminas-uri/src/Uri.php:389`
